import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Jumbotron from '../components/jumbotron/Jumbotron';
import Card from '../components/card/Card';
import Framer from '../components/framer/Framer';
import CardWrapper from '../components/card/CardWrapper';
// import styled from 'styled-components';

const Home: NextPage = () => {
	return (
		<div className='h'>
			<Head>
				<title>Trailix</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				{/* <h1> Hello there</h1> */}
				<Jumbotron
					title='Alaf the soothsayer'
					subTitle='A movie about alaf telling ultimate truths'
					imgUrl='/static/david.jpg'
				/>

				<CardWrapper>
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
					<Card imgUrl="/static/david.jpg" size="lg" />
				</CardWrapper>
				
				
			</div>
		</div>
	);
};

export default Home;

